version: '3.5'

services:
  $name;format="normalize"$-spark-master:
    image: osekoo/spark:3.5.0
    container_name: $name;format="normalize"$-spark-master
    build:
      context: ./
    environment:
      - SPARK_MODE=master
    ports:
      - '\${SPARK_MASTER_PORT:-7077}:\${SPARK_MASTER_PORT:-7077}'
      - '\${SPARK_WEBUI_PORT:-8080}:\${SPARK_WEBUI_PORT:-8080}'

  spark-worker:
    image: osekoo/spark:3.5.0
    env_file:
      - .env
    environment:
      - SPARK_MODE=worker
    deploy:
      replicas: \${SPARK_WORKERS:-2 }
    depends_on:
      - $name;format="normalize"$-spark-master

  $name;format="normalize"$-spark-submit:
    image: osekoo/spark:3.5.0
    container_name: $name;format="normalize"$-spark-submit
    env_file:
      - .env
    environment:
      - SPARK_MODE=submit
    ports:
      - '\${SPARK_APP_PORT:-4040}:\${SPARK_APP_PORT:-4040}'
    volumes:
      - "./:/app"
    depends_on:
      - spark-worker
